version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: server/Dockerfile
    container_name: chat-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: chat-client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - chat-network
    restart: unless-stopped

networks:
  chat-network:
    driver: bridge 